### ISSUE TITLE
Script flooding feed with old tweets

### ISSUE THREAD

**Issue by Retew** [ayush-sharma/tweet-toot#10]
Hi, today I've came across an issue with this script:

if it runs (I've got it set in Cron to every minute) and there are no new tweets after the ones it has already posted to Mastodon it posts older tweets from the same account and ends up flooding the feed with all the tweets from the target Twitter account in reversed chronological order.

I came up with an idea that it could use a separate var from config file that stores a "limiter" tweet URL beyond which script doesn't go and stops it's checking.

Unfortunately I'm just a beginner in programming and can't implement this solution myself due to a lack of skills, so I hope you could help.

Anyway, thank you for your work, it has been very useful so far.

Also it would be a cool option if it was possible to make multiple config files for different twitter accounts enabling user to run several twitter bridges for different accounts on a single machine simultaneously. Just a thought though...

**Comment by ayush-sharma** [comment]
I've made some changes to now check the last post by timestamp with the ID. This should fix your issue. Can you try this out for me? Could use some feedback.

https://github.com/ayush-sharma/tweet-toot/tree/fix-10

**Comment by Retew** [comment]
Which files should I replace exactly?

**Comment by ayush-sharma** [comment]
Just replacing helpers.py and social.py should do it.

**Comment by ayush-sharma** [comment]
@Retew I added one more fix to `social.py`. Can you download the file again? I'm sorry for the trouble.

**Comment by ayush-sharma** [comment]
Hi @Retew,

Hope the fix is working fine on your end. Let me know if that resolved the issue and I'll close this ticket.

Thanks,
Ayush.

**Comment by ayush-sharma** [comment]
@Retew I've merged the new code in the master and created new tag 1.8.

Let me know if this fixes this issue.
