### ISSUE TITLE
Hi, Is there a way to tweet multiple twitter accounts to one Mastodon account?

### ISSUE THREAD

**Issue by HolgerHuo** [ayush-sharma/tweet-toot#12]
Can I specify more than one twitter account in config.json?

**Comment by ayush-sharma** [comment]
Hi,

This particular feature is not supported. So far the use-case has been to cross-post one twitter account to one mastodon account.

For your use-case, you can run the app in 2 different docker containers, and configure different twitter accounts but the same mastodon account in each.

Can you try this?

**Comment by HolgerHuo** [comment]
Thank you so much. I'm currently using a shell to switch config.json and run the program one by one. To some degree, it solved my problem.
