### ISSUE TITLE
Script posting old tweets

### ISSUE THREAD

**Issue by 1011001-p** [ayush-sharma/tweet-toot#13]
Today I´ve found this cool script, however I think I found a bug that was already addressed before and I think I know why it keeps happening.

Issue: 
The script is posting old tweets.

Possible cause:
I used the docker image that is on dockerhub instead of cloning the git, maybe it´s outdated?

**Comment by 1011001-p** [comment]
I tried to replace the helpers.py and social.py and it worked so I can confidently say that the docker image is outdated.

**Comment by ayush-sharma** [comment]
Hi @1011001-p, thanks a lot for reporting this. I'll update the Docker image as soon as I can, and I'll try to figure out GitHub Actions to keep it up to date with new code changes going forward.

**Comment by ayush-sharma** [comment]
Hi @1011001-p,

I've updated the Docker image with the latest code:

https://hub.docker.com/layers/ayushsharma22/tweet-toot/2.0/images/sha256-49a63d3c49b1798545c3f959f99a2872967c18d070d9bd12a848058919d10103?context=repo

You should be able to run this by running:

```
export TT_APP_SECURE_TOKEN="<mastodon-token>"

docker run --rm -e TT_APP_SECURE_TOKEN="$TT_APP_SECURE_TOKEN" -v /tmp:/tmp ayushsharma22/tweet-toot:2.0
```

The new image works on some new code changes which can pick up Mastodon token from the environment. I'll be pushing the code in the repo soon.
